In [1]:
import pandas as pd
d = pd.read_csv('data/carprices.csv')
d

                Car Model  Mileage  Sell Price($)  Age(yrs)
0                  BMW X5    69000          18000         6
1                  BMW X5    35000          34000         3
2                  BMW X5    57000          26100         5
3                  BMW X5    22500          40000         2
4                  BMW X5    46000          31500         4
5                 Audi A5    59000          29400         5
6                 Audi A5    52000          32000         5
7                 Audi A5    72000          19300         6
8                 Audi A5    91000          12000         8
9   Mercedez Benz C class    67000          22000         6
10  Mercedez Benz C class    83000          20000         7
11  Mercedez Benz C class    79000          21000         7
12  Mercedez Benz C class    59000          33000         5

In [13]:
dummies = pd.get_dummies(d['Car Model'])
dummies

        0      1      2
0   False   True  False
1   False   True  False
2   False   True  False
3   False   True  False
4   False   True  False
5    True  False  False
6    True  False  False
7    True  False  False
8    True  False  False
9   False  False   True
10  False  False   True
11  False  False   True
12  False  False   True

In [14]:
merged = pd.concat([d, dummies], axis=1)
merged

    Car Model  Mileage  Sell Price($)  Age(yrs)      0      1      2
0           1    69000          18000         6  False   True  False
1           1    35000          34000         3  False   True  False
2           1    57000          26100         5  False   True  False
3           1    22500          40000         2  False   True  False
4           1    46000          31500         4  False   True  False
5           0    59000          29400         5   True  False  False
6           0    52000          32000         5   True  False  False
7           0    72000          19300         6   True  False  False
8           0    91000          12000         8   True  False  False
9           2    67000          22000         6  False  False   True
10          2    83000          20000         7  False  False   True
11          2    79000          21000         7  False  False   True
12          2    59000          33000         5  False  False   True

In [17]:
final = merged.drop(["Car Model",2],axis='columns')
final

    Mileage  Sell Price($)  Age(yrs)      0      1
0     69000          18000         6  False   True
1     35000          34000         3  False   True
2     57000          26100         5  False   True
3     22500          40000         2  False   True
4     46000          31500         4  False   True
5     59000          29400         5   True  False
6     52000          32000         5   True  False
7     72000          19300         6   True  False
8     91000          12000         8   True  False
9     67000          22000         6  False  False
10    83000          20000         7  False  False
11    79000          21000         7  False  False
12    59000          33000         5  False  False

In [18]:
X = final.drop('Sell Price($)',axis='columns')
X

    Mileage  Age(yrs)      0      1
0     69000         6  False   True
1     35000         3  False   True
2     57000         5  False   True
3     22500         2  False   True
4     46000         4  False   True
5     59000         5   True  False
6     52000         5   True  False
7     72000         6   True  False
8     91000         8   True  False
9     67000         6  False  False
10    83000         7  False  False
11    79000         7  False  False
12    59000         5  False  False

In [19]:
y = final['Sell Price($)']
y

0     18000
1     34000
2     26100
3     40000
4     31500
5     29400
6     32000
7     19300
8     12000
9     22000
10    20000
11    21000
12    33000
Name: Sell Price($), dtype: int64

In [20]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()

In [21]:
model.fit(X, y)

TypeError: Feature names are only supported if all input features have string names, but your input has ['int', 'str'] as feature name / column name types. If you want feature names to be stored and validated, you must convert them all to strings, by using X.columns = X.columns.astype(str) for example. Otherwise you can remove feature / column names from your input data, or convert them all to a non-string data type.

In [22]:
model.score(X,y)

NotFittedError: This LinearRegression instance is not fitted yet. Call 'fit' with appropriate arguments before using this estimator.

In [24]:
model.predict([[45000,4,0,0]])

NotFittedError: This LinearRegression instance is not fitted yet. Call 'fit' with appropriate arguments before using this estimator.

In [23]:
model.predict([[86000,7,0,1]])

NotFittedError: This LinearRegression instance is not fitted yet. Call 'fit' with appropriate arguments before using this estimator.